name: testando-banco-de-dados

services:
  pg:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=testeBanco
